openapi: 3.0.3
info:
  version: '1'
  title: API http-сервера GeoControl.
tags:
  - name: Auth
    description: Авторизация.
  - name: Users
    description: Операции над пользователями.
  - name: Map
    description: Операции, отражаемые на карте.
  - name: Chat
    description: Операции над чатом.

paths: 
  /api/auth:
    post:
      tags:
        - Auth
      summary: Авторизоваться.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequestData'
        description: Авторизационные данные - логин и пароль.
      responses:
        '200':
          description: Авторизация прошла успешно.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponseData'
        '400':
          description: Неверный логин или пароль.
        '500':
          description: Ошибка на стороне сервера.
          
components:
  schemas:
    AuthRequestData:
      description: Данные для авторизации.
      type: object
      required:
        - login
        - password
      properties:
        login:
          type: string
          example: "Anastasia"
          description: Пользовательский логин.
        password:
          type: string
          example: "Qwerty123"
          description: Пользовательский пароль.
    AuthResponseData:
      description: Ответ на успешную авторизацию.
      type: object
      required:
        - id
        - userType
      properties:
        id:
          type: string
          format: uuid
          example: "8F9619FF-8B86-D011-B42D-00CF4FC964FF"
          description: Идентификатор пользователя.
        userType:
          type: string
          enum:
            - PARENT
            - CHILD
          example: PARENT
          description: Тип данного пользователя - родитель или ребенок.
    